### ISSUE TITLE
Removal Candidate

### ISSUE THREAD

**Issue by Adurol** [KaOS-Community-Packages/clazy#1]
This Package will be removed in 7 days from KCP.

Reason: **Broken**
`==> ERROR: source should be an array`

Please see also: [Using KaOS Community Packages](https://kaosx.us/phpBB3/viewtopic.php?f=12&t=145) and [KCP Guide](https://kaosx.us/kcp-guide/)

**Comment by demmm** [comment]
Fixed with https://github.com/KaOS-Community-Packages/clazy/commit/6ca4ae006a79d99e63eecf48bd213101b966fdd8
